Repository bpmn-io/bpmn-js, pull requests merged in 2019-05, with the labels that each got.

#1012 Integrate Grid Snapping With Connection Layout
  lib/features/grid-snapping/behavior/LayoutConnectionBehavior.js
  lib/features/grid-snapping/behavior/index.js
  test/spec/features/grid-snapping/behavior/LayoutConnectionBehavior.bpmn
  test/spec/features/grid-snapping/behavior/LayoutConnectionBehaviorSpec.js
Labels: needs review

#1021 chore(bpmn-auto-resize): add test
  lib/features/auto-resize/BpmnAutoResize.js
  test/spec/features/grid-snapping/behavior/AutoResizeBehavior.bpmn
  test/spec/features/grid-snapping/behavior/AutoResizeBehaviorSpec.js
Labels: needs review

#1023 feat(bpmn-snapping): snap shape to itself
  lib/features/snapping/BpmnSnapping.js
  test/spec/features/snapping/BpmnSnapping.general.bpmn
  test/spec/features/snapping/BpmnSnappingSpec.js
Labels: needs review

#1026 Prevent expanded subprocess overlap of previous content
  lib/features/modeling/behavior/EventBasedGatewayBehavior.js
  lib/features/modeling/behavior/SubProcessBehavior.js
  lib/features/modeling/behavior/ToggleElementCollapseBehaviour.js
  lib/features/modeling/behavior/index.js
  test/spec/features/modeling/behavior/SubProcessBehavior.bpmn
  test/spec/features/modeling/behavior/SubProcessBehaviorSpec.js
Labels: enhancement, needs review

#1032 test(modeling/behavior): remove unnecessary sinon usage
  test/spec/features/modeling/behavior/SubProcessBehaviorSpec.js
Labels: needs review, test

#1028 Consistently layout connections previews
  lib/Modeler.js
  lib/features/connect/BpmnConnectPreview.js
  lib/features/connect/index.js
  lib/features/connection-preview/BpmnConnectionPreview.js
  lib/features/connection-preview/index.js
  lib/features/create/BpmnCreateConnectPreview.js
  lib/features/create/index.js
  test/spec/features/modeling/layout/LayoutConnectionSpec.js
Labels: needs review

#1036 fix(rules): do not allow message flows to outside diagram shapes
  lib/features/rules/BpmnRules.js
  test/spec/features/rules/BpmnRules.connectOnCreate.bpmn
  test/spec/features/rules/BpmnRulesSpec.js
Labels: needs review

#1029 fix(copy-paste): adjust categoryValueRef when group is copied
  lib/features/copy-paste/BpmnCopyPaste.js
  test/fixtures/bpmn/features/copy-paste/properties.bpmn
  test/spec/features/copy-paste/BpmnCopyPasteSpec.js
Labels: needs review

#1035 Fix Custom Elements Test
  lib/Modeler.js
  lib/features/connection-preview/BpmnConnectionPreview.js
  lib/features/connection-preview/index.js
  test/integration/custom-elements/CustomRules.js
  test/spec/features/modeling/layout/LayoutConnectionSpec.js
Labels: needs review

#1039 Add subprocess with start event included
  lib/features/modeling/behavior/SubProcessStartEventBehavior.js
  lib/features/modeling/behavior/index.js
  test/spec/features/modeling/behavior/SubProcessBehavior.start-event.bpmn
  test/spec/features/modeling/behavior/SubProcessStartEventBehaviorSpec.js
Labels: enhancement, needs review
